.travis.yml
Godeps/Godeps.json
influx/influx.go
scripts/test.sh

Fixed Issue#32. Now it's possible to modify published namespace according to metric Labels

Fix for Issue#32

---

.netrc
.travis.yml
Godeps/Godeps.json
influx/influx.go

Update godeps to work with latest versions of godep

---

influx/influx.go

Plugin version and year updated after fix for issue #38

Plugin version and year updated after fix for issue #38

---

influx/influx.go

Fix for issue #41, BatchPoints needs to have defined precision

---

influx/influx.go

Fixes #51 - Adds a connection pool for maintaining connections to InfluxDB. Connections are unique by user, db, and URL. A watching function closing idle connections (30min).

Adds a connection pool for maintaining connections.

---

influx/influx.go

This bumps the version based on the fix in #61

Bump version to match fix from #61

---

.travis.yml

Update from Intelsdi-x pluginsync 0.1.5

---

examples/tasks/mock-influxdb.sh

Changes:
Fix broken URL.
When an error occurs while downloading with curl it's going to display it.
Test done:
make test-large

Fixed the link and updated the curl request

---

influxdb/influxdb.go

Fixed plugin name

---

examples/tasks/docker-compose.yml
scripts/config/influxdb-deployment.yml

- use new apline_test containers to fix large test
Testing done:
- running large test

(maint) use new test containers

---

examples/tasks/README.md
examples/tasks/mock-influxdb.sh
examples/tasks/run-mock-influxdb.sh
scripts/large_tests.sh

- snapd changed to snapteld in large tests and in example
- snapctl changed to snaptel in large tests and in example
@intelsdi-x/plugin-maintainers

Updated Snap binaries in large tests and in example

---

examples/tasks/task-mock-influxdb.yml

- Fixes #94, adjusted exemplary task to Influxdb which is used in large tests
- large tests are running without errors

Fixes #94, adjusted exemplary task to Influxdb which is used in large tests

---

influxdb/influxdb.go

Updates version to 16

---

README.md
examples/tasks/.setup.sh
examples/tasks/README.md
examples/tasks/docker-compose.yml
examples/tasks/meminfo-influxdb.sh
examples/tasks/run-meminfo-influxdb.sh
examples/tasks/task-meminfo-influxdb.yml
scripts/config/docker-compose.yml
scripts/config/influxdb-deployment.yml
scripts/large_compose.sh
scripts/large_tests.sh
scripts/medium.sh

Updates support matrics, large tests and example
- updated support matrics for plugin, Snap and InfluxDB
- example uses meminfo collector instead of mock collector
- large tests updated to new version of InfluxDB and meminfo collector
- run large tests
Testing done:
- large tests
@intelsdi-x/plugin-maintainers

Updates support matrics and fixes example

---

README.md
influxdb/influxdb.go
influxdb/influxdb_medium_test.go
influxdb/influxdb_small_test.go
scripts/config/docker-compose.yml

Fixes: #106 
- added UDP support through the "scheme" config field
- updated README
- manually run small and medium tests
Testing done:
- small and medium
Note that: large test will be fixed after this and Nan's PRs are merged.

SDI-2374: Support writing data points using UDP client

---

.pluginsync.yml
.sync.yml
.travis.yml
CONTRIBUTING.md
Makefile
examples/tasks/psutil-influxdb-http.yml
examples/tasks/psutil-influxdb-udp.yml
scripts/common.sh
scripts/large.sh
scripts/test.sh
scripts/test/large_spec.rb
scripts/test/spec_helper.rb

- Updated large tests with pluginsync tool
Testing done:
- make test-small/medium/large

Update large tests with pluginsync v0.1.13

---

influxdb/influxdb.go

Fixes #117 
- Added creating of database if it does not exist.
- run with InfluxDB specifying in the task name of the database that does not exist yet.
Testing done:
- small tests

Added creation of database if it doesn't exist

---

influxdb/influxdb.go

Fixes #117 
- Added creation of database using http package instead of inluxdb client lib to workaround https://github.com/influxdata/influxdb/issues/8108 
- run tests
Testing done:
- small

Add creation of database using http instead of client library

---

.sync.yml
.travis.yml
glide.lock
glide.yaml
influxdb/influxdb.go
influxdb/influxdb_medium_test.go
influxdb/influxdb_small_test.go
main.go
scripts/medium.sh

Fixes #120 
- Migrated plugin to use new plugin lib
- Updated tests

Fixes #120 Migrated to new plugin lib go

---

influxdb/influxdb.go

Fixes #132 
- Check for database before, and skip creation if already exists
- Added TLS options to handle HTTPS
- Plugin with http and https should work
Testing done:
- Tested InfluxDB 1.2 with http and https (invalid certificates), noauth

Fix SSL insecure skip verify

---

README.md

Fixes #130
- added information about retention parameter
- check documentation

Fixes #130, added information about retention parameter

---

.travis.yml
CONTRIBUTING.md

Update from Intelsdi-x pluginsync 0.1.18
